In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import plotly.express as px
%matplotlib inline
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import sklearn
from scipy import stats
import os
import seaborn as sns

In [2]:
#goal: build a machine learning model to predict the selling prices of houses based on a variety of features on which the value of the house is evaluated.

#load and read the dataset, imported in excel format

In [3]:
data = pd.read_excel('regression_data.xls')
data.head()

id       date  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0  7129300520 2014-10-13         3       1.00         1180      5650     1.0   
1  6414100192 2014-12-09         3       2.25         2570      7242     2.0   
2  5631500400 2015-02-25         2       1.00          770     10000     1.0   
3  2487200875 2014-12-09         4       3.00         1960      5000     1.0   
4  1954400510 2015-02-18         3       2.00         1680      8080     1.0   

   waterfront  view  condition  grade  sqft_above  sqft_basement  yr_built  \
0           0     0          3      7        1180              0      1955   
1           0     0          3      7        2170            400      1951   
2           0     0          3      6         770              0      1933   
3           0     0          5      7        1050            910      1965   
4           0     0          3      8        1680              0      1987   

   yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15   price  
0             0    98178  47.5112 -122.257           1340        5650  221900  
1          1991    98125  47.7210 -122.319           1690        7639  538000  
2             0    98028  47.7379 -122.233           2720        8062  180000  
3             0    98136  47.5208 -122.393           1360        5000  604000  
4             0    98074  47.6168 -122.045           1800        7503  510000

In [4]:
for col in data.columns:
    print(col)

id
date
bedrooms
bathrooms
sqft_living
sqft_lot
floors
waterfront
view
condition
grade
sqft_above
sqft_basement
yr_built
yr_renovated
zipcode
lat
long
sqft_living15
sqft_lot15
price


In [5]:
#the for loop above is used in order to identify al the columns within the dataset. id is a non-relevant column for the ML model that we want to build, however, it will be essential for the sql db when we perform the neccesary queries. 

In [6]:
check_nan = data.isnull().values.any()
print(check_nan)

False


In [7]:
# we check for NaN in the dataset, and we can't find any

In [8]:
# we find the unique values within the "bedrooms", "bathrooms", "waterfront view", "condition" and "grade"

In [9]:
data.bedrooms.unique()

array([ 3,  2,  4,  5,  1,  6,  7,  8,  9, 11, 10, 33], dtype=int64)

In [10]:
data.bathrooms.unique()

array([1.  , 2.25, 3.  , 2.  , 4.5 , 1.5 , 2.5 , 1.75, 2.75, 3.25, 4.  ,
       3.5 , 0.75, 4.75, 5.  , 4.25, 3.75, 1.25, 5.25, 6.  , 0.5 , 5.5 ,
       6.75, 5.75, 8.  , 7.5 , 7.75, 6.25, 6.5 ])

In [11]:
# we note that the "number of bathrooms" variable, which is expected to take a discrete range of values, behaves like a continuous one

In [12]:
data.waterfront.unique()

array([0, 1], dtype=int64)

In [13]:
data.view.unique()

array([0, 3, 4, 2, 1], dtype=int64)

In [14]:
data.condition.unique()

array([3, 5, 4, 1, 2], dtype=int64)

In [15]:
data.grade.unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13], dtype=int64)

In [16]:
#regarding the "date" variable, we have considered interesting 'disaggregating' this value into DD,MM,YY, to 'play' with the later statistical analysis that we will later perform in Tableau for data visualization. 

In [17]:
date = data["date"] 
data['month']=data['date'].dt.month 
data['day']=data['date'].dt.day
data['year']=data['date'].dt.year

In [18]:
# delete the 'id' field as it is not required for the ML model 

In [19]:
data2 = data.drop(['id'], axis=1)
data2

date  bedrooms  bathrooms  sqft_living  sqft_lot  floors  \
0     2014-10-13         3       1.00         1180      5650     1.0   
1     2014-12-09         3       2.25         2570      7242     2.0   
2     2015-02-25         2       1.00          770     10000     1.0   
3     2014-12-09         4       3.00         1960      5000     1.0   
4     2015-02-18         3       2.00         1680      8080     1.0   
...          ...       ...        ...          ...       ...     ...   
21592 2014-05-21         3       2.50         1530      1131     3.0   
21593 2015-02-23         4       2.50         2310      5813     2.0   
21594 2014-06-23         2       0.75         1020      1350     2.0   
21595 2015-01-16         3       2.50         1600      2388     2.0   
21596 2014-10-15         2       0.75         1020      1076     2.0   

       waterfront  view  condition  grade  sqft_above  sqft_basement  \
0               0     0          3      7        1180              0   
1               0     0          3      7        2170            400   
2               0     0          3      6         770              0   
3               0     0          5      7        1050            910   
4               0     0          3      8        1680              0   
...           ...   ...        ...    ...         ...            ...   
21592           0     0          3      8        1530              0   
21593           0     0          3      8        2310              0   
21594           0     0          3      7        1020              0   
21595           0     0          3      8        1600              0   
21596           0     0          3      7        1020              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955             0    98178  47.5112 -122.257           1340   
1          1951          1991    98125  47.7210 -122.319           1690   
2          1933             0    98028  47.7379 -122.233           2720   
3          1965             0    98136  47.5208 -122.393           1360   
4          1987             0    98074  47.6168 -122.045           1800   
...         ...           ...      ...      ...      ...            ...   
21592      2009             0    98103  47.6993 -122.346           1530   
21593      2014             0    98146  47.5107 -122.362           1830   
21594      2009             0    98144  47.5944 -122.299           1020   
21595      2004             0    98027  47.5345 -122.069           1410   
21596      2008             0    98144  47.5941 -122.299           1020   

       sqft_lot15   price  month  day  year  
0            5650  221900     10   13  2014  
1            7639  538000     12    9  2014  
2            8062  180000      2   25  2015  
3            5000  604000     12    9  2014  
4            7503  510000      2   18  2015  
...           ...     ...    ...  ...   ...  
21592        1509  360000      5   21  2014  
21593        7200  400000      2   23  2015  
21594        2007  402101      6   23  2014  
21595        1287  400000      1   16  2015  
21596        1357  325000     10   15  2014  

[21597 rows x 23 columns]

In [20]:
# provide a description of the dataset 

In [21]:
data2.describe()

bedrooms     bathrooms   sqft_living      sqft_lot        floors  \
count  21597.000000  21597.000000  21597.000000  2.159700e+04  21597.000000   
mean       3.373200      2.115826   2080.321850  1.509941e+04      1.494096   
std        0.926299      0.768984    918.106125  4.141264e+04      0.539683   
min        1.000000      0.500000    370.000000  5.200000e+02      1.000000   
25%        3.000000      1.750000   1430.000000  5.040000e+03      1.000000   
50%        3.000000      2.250000   1910.000000  7.618000e+03      1.500000   
75%        4.000000      2.500000   2550.000000  1.068500e+04      2.000000   
max       33.000000      8.000000  13540.000000  1.651359e+06      3.500000   

         waterfront          view     condition         grade    sqft_above  \
count  21597.000000  21597.000000  21597.000000  21597.000000  21597.000000   
mean       0.007547      0.234292      3.409825      7.657915   1788.596842   
std        0.086549      0.766390      0.650546      1.173200    827.759761   
min        0.000000      0.000000      1.000000      3.000000    370.000000   
25%        0.000000      0.000000      3.000000      7.000000   1190.000000   
50%        0.000000      0.000000      3.000000      7.000000   1560.000000   
75%        0.000000      0.000000      4.000000      8.000000   2210.000000   
max        1.000000      4.000000      5.000000     13.000000   9410.000000   

       sqft_basement      yr_built  yr_renovated       zipcode           lat  \
count   21597.000000  21597.000000  21597.000000  21597.000000  21597.000000   
mean      291.725008   1970.999676     84.464787  98077.951845     47.560093   
std       442.667800     29.375234    401.821438     53.513072      0.138552   
min         0.000000   1900.000000      0.000000  98001.000000     47.155900   
25%         0.000000   1951.000000      0.000000  98033.000000     47.471100   
50%         0.000000   1975.000000      0.000000  98065.000000     47.571800   
75%       560.000000   1997.000000      0.000000  98118.000000     47.678000   
max      4820.000000   2015.000000   2015.000000  98199.000000     47.777600   

               long  sqft_living15     sqft_lot15         price         month  \
count  21597.000000   21597.000000   21597.000000  2.159700e+04  21597.000000   
mean    -122.213982    1986.620318   12758.283512  5.402966e+05      6.573969   
std        0.140724     685.230472   27274.441950  3.673681e+05      3.115061   
min     -122.519000     399.000000     651.000000  7.800000e+04      1.000000   
25%     -122.328000    1490.000000    5100.000000  3.220000e+05      4.000000   
50%     -122.231000    1840.000000    7620.000000  4.500000e+05      6.000000   
75%     -122.125000    2360.000000   10083.000000  6.450000e+05      9.000000   
max     -121.315000    6210.000000  871200.000000  7.700000e+06     12.000000   

                day          year  
count  21597.000000  21597.000000  
mean      15.687457   2014.322962  
std        8.634890      0.467619  
min        1.000000   2014.000000  
25%        8.000000   2014.000000  
50%       16.000000   2014.000000  
75%       23.000000   2015.000000  
max       31.000000   2015.000000

In [22]:
# separate the numerical and categorical dataset 

In [23]:
num = data2.select_dtypes(include=np.number)
print(num)

       bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0   
1             3       2.25         2570      7242     2.0           0     0   
2             2       1.00          770     10000     1.0           0     0   
3             4       3.00         1960      5000     1.0           0     0   
4             3       2.00         1680      8080     1.0           0     0   
...         ...        ...          ...       ...     ...         ...   ...   
21592         3       2.50         1530      1131     3.0           0     0   
21593         4       2.50         2310      5813     2.0           0     0   
21594         2       0.75         1020      1350     2.0           0     0   
21595         3       2.50         1600      2388     2.0           0     0   
21596         2       0.75         1020      1076     2.0           0     0   

       condition  grade  sqft_above  sqft_basement 

In [24]:
cat = data2.select_dtypes(exclude=np.number)
print(cat)

            date
0     2014-10-13
1     2014-12-09
2     2015-02-25
3     2014-12-09
4     2015-02-18
...          ...
21592 2014-05-21
21593 2015-02-23
21594 2014-06-23
21595 2015-01-16
21596 2014-10-15

[21597 rows x 1 columns]


In [25]:
# as discussed, these are the variables that are going to be treated as 'discrete' and 'continuous' 

continous = sqft_living, sqft_lot, sqft_above, sqft_basement, yr_built, yr_renovated, zipcode, lat, long, sqft_living15, sqft_lot15, price (target), month_bought, year_bought
discrete = bedrooms, bathrooms, floors, waterfront, view, condition, grade

bedrooms
bathrooms
sqft_living
sqft_lot
floors
waterfront
view
condition
grade
sqft_above
sqft_basement

In [26]:
# plot the outliers chart for the below mentioned variables: 

In [27]:
#here we represent all the variables in a pair-plot

In [ ]:
sns.pairplot(num)

In [ ]:
sns.pairplot(num, kind = "reg")

In [ ]:
sns.pairplot(
    num,
    x_vars=["bedrooms", "bathrooms", "sqft_living","sqft_lot","floors","waterfront"],
    y_vars=["price"],
)